### ISSUE TITLE
Include options to format and reject empty periods.

### ISSUE THREAD

**Issue by gjhenrique** [lukeed/fromnow#5]
Hello

I'm using this library for the notification box of a project.
So whenever an user event pops up, I need to show it with the past time ("1m ago", "1d ago" or "6m ago").

I'm already using the `max` option to show only the "nearest" date, but I am getting empty date parts like `0 years, 0 months`

I'm opening a PR with these two options:
1. The option `rejectEmptyPeriod`, if set to true, only allows periods that are bigger than 0.
2. The option `dateFormatter` allows you to pass the value and the period and the user configures the format of that period.

Do you think this is useful?

**Comment by jpodwys** [comment]
@lukeed I would also like to ignore empty periods. In fact, aside from it representing a potentially breaking change, it seems like `fromNow` ought to omit "0 years" and such from the output by default. I'm certain I don't understand everyone's needs, so avoiding a breaking change with the `rejectEmptyPeriod ` option may be good, but I'm not aware of a scenario in which it's useful to know something happened "0 years and 11 months ago".

If you agree, we can just change this line:

`if (chunks[i] && limit < max) {`

to 

`if (chunks[i] && limit < max && chunks[i][0] !== '0') {`

or

`if (chunks[i] && limit < max && chunks[i].split(' ')[0] !== '0') {`

Thoughts?
